version: '3'
services:
  db:
    image: postgres
  mongo:
    image: mongo:3.4.5
    ports:
      - "27017:27017"
  web:
    build: .
    volumes:
      - .:/hello_world
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mongo
