version: '3'
services:
  db:
    image: postgres
  mongodb:
    image: mongo:3.4.5
    command: mongod --smallfiles
    ports:
      - "27017:27017"
  web:
    build: .
    volumes:
      - .:/hello_world
    ports:
      - "3000:3000"
    links:
      - mongodb 
    depends_on:
      - db
