# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f8cc66b6fea535e65971a4b921141a093af83c7193000d2087d792307b7f380c05ee4c76b4d0ed84871d95646379dc3a3b4f7628c8f9ce18627dd271722cb0b

test:
  secret_key_base: 544eb01ab93399a89c17bfba03cfcc1bb02fe89ee2f41c6a54afe78a5e46d1c38c829ff42332ed61cb5cbbae40fe8ec86b31fe876f0a1ff6f5a99c34cb53bdc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
